# Generated by Django 2.2.3 on 2019-07-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
